# Generated by Django 4.2.2 on 2023-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='3.JPG', null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
