# Generated by Django 4.2.2 on 2023-06-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='mainimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
