# Generated by Django 4.2.2 on 2023-06-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
