# Generated by Django 4.2.2 on 2023-06-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
