# Generated by Django 4.2.2 on 2023-06-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0025_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartItems', to='ecomm.cart'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
