# Generated by Django 4.2.2 on 2023-06-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0028_remove_customer_user_customer_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
    ]
