# Generated by Django 4.0.3 on 2023-06-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0032_remove_shippingaddress_order_order_ship_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='Street_address',
        ),
    ]
