# Generated by Django 4.2.2 on 2023-06-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0033_rename_address_shippingaddress_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Street_address',
            new_name='street_address',
        ),
    ]
