# Generated by Django 4.2.2 on 2023-06-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0034_rename_street_address_shippingaddress_street_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='CustomerAddress',
        ),
    ]
